# Site settings
title: Welcome
description: A software development website
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Ron Lawton
user_description: I am a recent graduate of the Bachelor of Science in Information Technology program at University of Phoenix. This website was created to provide acces to some of the projects I have been involved with.
user_title: Junior Software Developer
email: rlawton1234@gmail.com
github_username:  rlawton2

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
