# Site settings
title: Ronnie Lawton's Projects
description: A demonstation website
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Ron Lawton
user_description: This site was created to demonstate a working knowledge of software development.
user_title: Software Developer
email: rlawton1234@gmail.com
twitter_username: lorem_ipsum
github_username:  rlawton2
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
