# Site settings
title: Welcome
description: A site dedicated to software development
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Ron Lawton
user_description: I am a Unversity of Phoenix graduate with a Bachelors in Information Technology and Advanced Software Development certificate. What attracts me to software development is I enjoy finding solutions to problems and exploring new technologies. While going to school I wanted to understand other areas connected with development like project management and network communications. I pursued CompTIA training and received certificates in both Project+ and Network+. 
user_title: Software Developer
email: rlawton1234@gmail.com
github_username:  rlawton2

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
