# Site settings
title: Ronnie Lawton's website
description: A software development website
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Ronnie Lawton
user_description: This website was created to demonstrate my wokring knowledge in software development.
user_title: Software Developer
email: rlawton1234@gmail.com
github_username:  rlawton2

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
